language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
    packages:
      - libelf-dev
      - linux-headers-3.13.0-100-generic

script:
 - make -C driver check
 - KERNEL_VERSION=3.13.0-100-generic make -C driver
