#!/bin/bash
# SI 0000:05:00.0, major 254 minor 0 devfn 0 irq 209 isopen 0
#

MAJOR=` cat /proc/si3097 | awk '{ print $4 }' `
MINOR=` cat /proc/si3097 | awk '{ print $6 }' `

rm -f /dev/si3097*
mknod /dev/si3097a c $MAJOR $MINOR
chmod a+rw /dev/si3097a
echo created /dev/si3097a at $MAJOR $MINOR


